import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/layout/side-bar";
import { Providers } from "./providers";

const mont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shelley Bressman Photography",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mont.className} antialiased bg-[#e1dcd8] flex `}>
        <Providers>
          <aside className="flex-grow-0">
            <Sidebar />
          </aside>
          <main className="grow">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
