import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import '../globals.css'
import {Sidebar} from '@/components/layout/side-bar'
import {Providers} from '../providers'
import {Navbar} from '@/components/layout/navbar'
import {CSPostHogProvider} from '../providers'

const mont = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Shelley Bressman Photography',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Providers>
        <CSPostHogProvider>
          <body
            className={`${mont.className} antialiased bg-[#e1dcd8] flex h-screen max-h-screen  lg:overflow-hidden flex-col md:flex-row`}
          >
            <aside className="md:w-1/4 w-full bg-white md:relative fixed max-h-[117.75px] md:h-screen md:max-h-screen overflow-y-auto z-50">
              <Sidebar />
              <Navbar />
            </aside>
            <main className="grow md:w-3/4 md:h-screen md:pt-0 pt-[92px] w-full md:overflow-y-scroll ">
              {children}
            </main>
          </body>
        </CSPostHogProvider>
      </Providers>
    </html>
  )
}
